import {KFBoolean} from './support'

export interface Customer{
  CustomerID: number
  Code: string
  Name: string
  Contact: string
  Telephone: string
  Mobile: string
  Fax: string
  Email: string
  Address1: string
  Address2: string
  Address3: string
  Address4: string
  CountryName: string
  CountryCode: string
  Postcode: string
  Website: string
  EC: KFBoolean
  OutsideEC: KFBoolean
  Notes: string
  Source: number
  Discount: number
  ShowDiscount: boolean
  PaymentTerms: number
  ExtraText1: string
  ExtraText2: string
  ExtraText3: string
  ExtraText4: string
  ExtraText5: string
  ExtraText6: string
  ExtraText7: string
  ExtraText8: string
  ExtraText9: string
  ExtraText10: string
  ExtraText11: string
  ExtraText12: string
  ExtraText13: string
  ExtraText14: string
  ExtraText15: string
  ExtraText16: string
  ExtraText17: string
  ExtraText18: string
  ExtraText19: string
  ExtraText20: string
  CheckBox1: string
  CheckBox2: string
  CheckBox3: string
  CheckBox4: string
  CheckBox5: string
  CheckBox6: string
  CheckBox7: string
  CheckBox8: string
  CheckBox9: string
  CheckBox10: string
  CheckBox11: string
  CheckBox12: string
  CheckBox13: string
  CheckBox14: string
  CheckBox15: string
  CheckBox16: string
  CheckBox17: string
  CheckBox18: string
  CheckBox19: string
  CheckBox20: string
  Created: Date
  Updated: Date
  CurrencyID: number
  ContactTitle: string
  ContactFirstName: string
  ContactLastName: string
  CustHasDeliveryAddress: KFBoolean
  DeliveryAddress1: string
  DeliveryAddress2: string
  DeliveryAddress3: string
  DeliveryAddress4: string
  DeliveryCountryName: string
  DeliveryCountryCode: string
  DeliveryPostcode: string
  VATNumber: string
}